### ISSUE TITLE
export completed objects even in case of error

### ISSUE THREAD

**Issue by FabianRoger** [lindeloev/job#18]
I ran a large job that took several hours to complete. When trying to save the result an error was raised (see #19) and the results were lost. 

Would it be possible to catch the error and still export the results?

repex:
```
job::job({
  
  test <- rnorm(10)
  "B"+1 #will raise an error
  
  
})
```

the `test` object is not exported

**Comment by lindeloev** [comment]
I'll look into it. I guess this will be a common problem because jobs are used for expensive tasks, so the loss due to error is so much greater. 

I suspect that if we wrap the code in `try`, then we have no way to signal to RStudio that it should have failed status.

**Comment by lindeloev** [comment]
OK, I've failed so far to find a solution. If I can only get the job ID from within the job session, it could work. Let's see if I get any responses at the RStudio forum: https://community.rstudio.com/t/get-job-id-from-within-a-job/103384

Until then, try wrapping the code in `try()`, like

```
job::job({
  try({
     precious_result = "It took a long time computing me"
     stop("terrible failure!")
  })
})
```

This should `precious_result`, even though there was en error.

**Comment by lindeloev** [comment]
Tracking in #24 that the `try({})` trick should be documented. Closing.
