### ISSUE TITLE
Path inside a job

### ISSUE THREAD

**Issue by FabianRoger** [lindeloev/job#19]
I work with RStudio Projects and am used to construct my relative path with `here::here()`. I tried to use this to save a large object that I ran with `job::job` but the saving failed and all results were lost. 

The saving failed as the base directory of `here` changed to a temporary directory. 

```
here() starts at /tmp/RtmpTjtK75
```

I will use absolute path from now on but I just thought it might be good to know that this might be a problem for some people. 

Thanks for your very useful package!

**Comment by lindeloev** [comment]
The job is "prepared" using `setwd()` to the `getwd()` of the calling environment. But the script file itself is in a temp folder to avoid name clashes and to ensure that the temporary script- and data-files are deleted, even in case of crashes etc, I feel that this is the best solution, but LMK if you have ideas.

What do you think would be the best format documenting this, along perhaps with the `try()` idea of #18? A "tips and tricks" / FAQ section in the README?

**Comment by FabianRoger** [comment]
I guessed something along the lines, so I guess just pointing out that `here`won't work is the solution in this case. 

unless this could be solved on the `here`side of things? Ping @krlmlr, would that be possible?

Re the documentation I am a big fan of markdown tutorials linked form the github page (see [dada2](https://benjjneb.github.io/dada2/tutorial_1_8.html) for an example - of course it can be much more concise in this case). But that's just me. 

Thanks for the very useful package!

**Comment by lindeloev** [comment]
Thanks for the feedback. Yes, as I'm expanding/refining the functionality these days, I also think I'll make a `pkgdown` page with some walk-throughs. I'm closing this issue for now and will open a new one on a website.

**Comment by krlmlr** [comment]
From what I read here, it should work as long as the current working directory is somewhere below the project root.

**Comment by lindeloev** [comment]
Hi @FabianRoger. `here` now works in jobs. See #40.
