### ISSUE TITLE
play nice with here() package

### ISSUE THREAD

**Issue by fusaroli** [lindeloev/job#40]
Very minor issue. I often use the here() package, in particular when setting file= in brms.

This creates issues with job, since job doesn't seem to import the working directory and therefore cannot find the directory in which the model should be saved.

Again, not a huge issue.

**Comment by lindeloev** [comment]
The job simply setwd() to the getwd() of the calling environment. The job file is a tempfile() located elsewhere.

Is there something we could include/import before running user code in the job script that would make "here" act as if it was "home"?

The here package should not be a dependency, but we can definitely execute stuff in case it is installed.

**Comment by lindeloev** [comment]
Although I'm not familiar with `here`, it behaves as I would expect on my end (Windows + Mac). If you run

```r
job::job({
   print(here::here("subfolder", "filename.csv")
})
```

do you get a different path than expected?

**Comment by fusaroli** [comment]
darn, I should have learned by now to do reprex from the very start :-) sorry.

Here (slightly modified from the readme):

```
library(brms)
data = mtcars[mtcars$hp > 100, ]
model = mpg ~ hp * wt

# Send long-running code to a job
job::job(test = {
  options(mc.cores = 3)  # Set options inside the job
  fit = brm(model, data, file=here("models","test_m"))
  fit = add_criterion(fit, "loo")
  
  print(summary(fit))  # Show a summary in the job
  the_test = hypothesis(fit, "hp > 0")
  job::export(c(fit, the_test))  # Only return these
})

cat("I'm free now! Thank you.
    Sincerely, Console.")
```

models is a subdir in my wd.
I get:

> Error: The directory '/private/var/folders/3m/f039n0x549vfxhdtj55yykzhfjr0d6/T/RtmpHs0XM8/models' does not exist. Please choose an existing directory where the model can be saved after fitting.
> Execution halted

**Comment by lindeloev** [comment]
OK, now I see why it seemed to work OK here. If you never call `library(here)` in your session, it seems to work fine:

```
# library(here)
job::job({
    print(here::here("my_folder", "my_file.txt"))
})
```

One cannot change the `here` root dir without changing internal functions in `here`: https://github.com/r-lib/here/issues/19#issuecomment-521329729. Because they have no public API, they are more susceptible to change-without-notice. So I'm in a bind between 

1. Saving stuff in the current workfolder (dangerous), 
2. Relying on non-API (can be hard to maintain, but probably OK).
3. That the default usage of `here` won't work (but `here::here()` does if `library(here)` is not called.

LMK if you have any ideas for a better fourth way!

**Comment by lindeloev** [comment]
Incubation is great! I think I found a way that's not too terrible. Will implement properly later. Notes to self:

```r
# User code in main session
library(here)
print(here())

# Within job::job(), prepping for launching job
if ("here" %in% .packages()) {
  here_to_job = get(".root_env", envir = getNamespace("here"))  # Pass R CMD Check
}

job::job({
  # After `library()` but before user code
  if ("here" %in% .packages()) {
    assignInNamespace(".root_env", here_to_job, "here")
  }
  rm(here_to_job)
  
  # User code
  print(here::here("models", "stuff.txt"))
})
```

**Comment by lindeloev** [comment]
Could you try `remotes::install_github("lindeloev/job@dev")` and test the `here` behavior? It seems to behave as you requested now.

The solution turned out to be incredibly simple. Inside the job, `setwd()` BEFORE importing packages. Avoids `here`-specific code altogether.

**Comment by fusaroli** [comment]
all in place now :-)
