### ISSUE TITLE
failed to install the package

### ISSUE THREAD

**Issue by xtbgtraining** [lindeloev/job#41]
Whan I try to install the package using ”remotes::install_github("lindeloev/job")“
I got error 
Error: Failed to install 'unknown package' from GitHub:
  Line starting 'Config/testthat/edit ...' is malformed!

Could you guide me how to solve this and install the package ？

Jingxin

**Comment by lindeloev** [comment]
It throws an error at a fairly standard line of code. Things to try:

 1. Do you get the same error if you do `remotes::install_github("r-lib/here")`? It has a similar DESCRIPTION file. 
 2. If you run an old version of `remotes` or `pkgbuild`, try `install.packages(c("remotes", "pkgbuild"))`. After restarting R, does it then work?

Either way, could you post your `sessionInfo()`?

**Comment by xtbgtraining** [comment]
> It throws an error at a fairly standard line of code. Things to try:
> 
> 1. Do you get the same error if you do `remotes::install_github("r-lib/here")`? It has a similar DESCRIPTION file.
> 2. If you run an old version of `remotes` or `pkgbuild`, try `install.packages(c("remotes", "pkgbuild"))`. After restarting R, does it then work?
> 
> Either way, could you post your `sessionInfo()`?

## thanks for your quick reply !!
1） remotes::install_github("r-lib/here") worked, and I installed ”here“
2） I am using the latest version of remotes_2.3.0 and pkgbuild_1.2.0 , I guess, anyway I reinstalled them by "install.packages(c("remotes", "pkgbuild"))", but I still got the same error.

Here are the sessionInfo() 
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magrittr_2.0.1     mirrorselect_0.0.2

loaded via a namespace (and not attached):
 [1] ps_1.6.0          prettyunits_1.1.1 withr_2.4.2       rprojroot_2.0.2   crayon_1.4.1      R6_2.5.0         
 [7] cli_2.5.0         curl_4.3.1        rstudioapi_0.13   remotes_2.3.0     callr_3.7.0       tools_4.1.0      
[13] tinytex_0.32      xfun_0.23         compiler_4.1.0    processx_3.5.2    pkgbuild_1.2.0   

Thanks !!

**Comment by lindeloev** [comment]
That looks OK. Hmm, I'm somewhat clueless, so here's a not very likely solution: I wonder if it has something to do with your locale in combination with my name, like #30. Could you try the same solution that worked there, i.e., running this before install?

```r
Sys.setlocale("LC_MESSAGES", 'en_GB.UTF-8')
Sys.setenv(LANG = "en_US.UTF-8")
```

**Comment by xtbgtraining** [comment]
thanks, but failed still
> Sys.setlocale("LC_MESSAGES", 'en_GB.UTF-8')
[1] ""
Warning messages:
1: In Sys.setlocale("LC_MESSAGES", "en_GB.UTF-8") :
  LC_MESSAGES exists on Windows but is not operational
2: In Sys.setlocale("LC_MESSAGES", "en_GB.UTF-8") :
  OS reports request to set locale to "en_GB.UTF-8" cannot be honored
> Sys.setenv(LANG = "en_US.UTF-8")
> remotes::install_github("lindeloev/job")
Error: Failed to install 'unknown package' from GitHub:
  Line starting 'Config/testthat/edit ...' is malformed!

> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.1.0 tools_4.1.0    curl_4.3.1     remotes_2.3.0  tinytex_0.32   xfun_0.23

## but finally I downloaded "job-master" and complied it in cmd with R CMD build then installed locally.

Hurry!!
Thanks!!

**Comment by lindeloev** [comment]
Great that it's working, @xtbgtraining! It would be helpful for others who encounter this problem if you could reply with a step-by-step list of what you did. Did you start by clicking "download Zip" here on GitHub and then what R/bash code did you run to build it locally?

**Comment by xtbgtraining** [comment]
> Great that it's working, @xtbgtraining! It would be helpful for others who encounter this problem if you could reply with a step-by-step list of what you did. Did you start by clicking "download Zip" here on GitHub and then what R/bash code did you run to build it locally?

yes, my pleasure to share my steps!
![微信图片_20210601233135](https://user-images.githubusercontent.com/36725112/120351153-35017080-c332-11eb-8a03-0b6c67a7635d.png)
![QQ截图20210601233710](https://user-images.githubusercontent.com/36725112/120351375-69752c80-c332-11eb-80e7-61b489a80fae.png)
