### ISSUE TITLE
brms

### ISSUE THREAD

**Issue by colindaven** [lindeloev/job#5]
Hi,

interesting package, sure it will be popular. 

One note - since it is of general interest, it might be good to have a general package as an example. Alternatively, it would be worth mentioning 
`install.packages("brms") 
`
if not already done.

Oh, and on Debian/Ubuntu
`sudo apt install libv8-dev`

This caught me out as a non-brms user.

thanks

**Comment by lindeloev** [comment]
Good point. Will update. Just need to think of a typical long-running function in base R. Hmm...

**Comment by lindeloev** [comment]
I just updated the README with a base-R example first.

**Comment by colindaven** [comment]
Works nicely, cheers
