### ISSUE TITLE
job returns error when using NA_real_

### ISSUE THREAD

**Issue by stonekate** [lindeloev/job#51]
Hi Jonas, thanks for such a great package. I have a strange little issue when I try to use NA_real_ inside `dplyr::case_when` in `job`:

```
library(dplyr)
library(job)
    
(df <- data.frame(cond = c("a","b","c")))

# works outside job    
mutate(df, item = case_when(cond == "a" ~ 1,
                            cond == "b" ~ 2,
                            cond == "c" ~ NA_real_))

# error inside job
job({mutate(df, item = case_when(cond == "a" ~ 1,
                            cond == "b" ~ 2,
                            cond == "c" ~ NA_real_))})
```

The traceback suggests NA_real_ is still being treated as NA, which `case_when` doesn't like (it needs all assigned values to be of the same type):

![grafik](https://user-images.githubusercontent.com/12735809/197968609-5040e028-a917-499f-bf7e-f34c2dc610ad.png)

**Comment by lindeloev** [comment]
Whoa, thanks for posting a nice reproducible example. I don't currently have a nice solution, only an even more minimal replication. All of these lose their type when running in a job:

```r
job::job({
  print(class(NA))
  print(class(NA_real_))
  print(class(NA_character_))
  print(class(NA_integer_))
})
```

**Comment by stonekate** [comment]
Curious!

**Comment by lindeloev** [comment]
@stonekate A bugfix release is up on CRAN and I managed to solve this bug (I hope!).

**Comment by stonekate** [comment]
nice, thanks!
