### ISSUE TITLE
Equivalent of Seurat's IntegrateData parameter, features.to.integrate in Runharmony

### ISSUE THREAD

**Issue by akhst7** [lindeloev/job#52]
Hi, 

Is there a parameter in `Runharmony` similar to the Seurat's `IntegrateData` parameter, `features.to.integrate` ?

**Comment by lindeloev** [comment]
This seems to be related to another package (perhaps [harmony](https://github.com/immunogenomics/harmony)?), not `job`. Rephrase and reopen if this is a bug or feature request for `job`, thanks.
