### ISSUE TITLE
'Run selection as job' changes the search path (compared to interactive use)

### ISSUE THREAD

**Issue by rasmusrhl** [lindeloev/job#53]
* Using the plugin for Rstudio to 'Run selection as job' changes the search path, compared to interactive use.
* The effect is a different masking of functions. 
* This means that `set_names` may refer to `rlang::set_names` in interactive use,  but to `magrittr::set_names` in a job.
* This causes code that works interactively, to fail as a job.

# Example
Running this code interactively will have `rlang` prioritized in the search path (masking `magrittr`).
But running this code as a job will have `magrittr` prioritized in the search path (masking `rlang`). 

```
library(magrittr)
library(rlang)
searchpaths() |> print()

```

It would be nice if `job` could somehow use the same search path as in interactive use 😁

**Comment by lindeloev** [comment]
Hi @rasmusrhl. A bugfix release was just released on CRAN and it should have fixed this issue?
