### ISSUE TITLE
Support for Slurm system

### ISSUE THREAD

**Issue by xiachenrui** [lindeloev/job#54]
Hi,

This is a wonderful tool. I want to know if it support submit job to annother machine or slurm cluster.

Best !

**Comment by lindeloev** [comment]
Hi @xiachenrui. Sorry for the very slow reply 😅, but no, `{job}` is just for spinning up parallel sessions as jobs within RStudio (whether run locally or on Posit Workbench). Check out packages like `{future}`, `{callr}`, and maybe even `[targets}` (which uses `{crew}`) for ways of orchestrating jobs across machines/clusters independently of whether it's executed from RStudio.
