### ISSUE TITLE
RStudio addins

### ISSUE THREAD

**Issue by wlandau** [lindeloev/job#6]
Awesome package!

What are your plans for RStudio addins? Some possibilities that come to mind:

1. Launch the current script as a job.
2. Launch highlighted text.
3. Launch the command at the cursor.

**Comment by lindeloev** [comment]
Nice idea, hadn't thought of it! You can already launch the current script as a job.
![image](https://user-images.githubusercontent.com/1439417/116079477-23c0a680-a698-11eb-83b0-cf7115c06cd9.png)

But the two others would be great.

**Comment by lindeloev** [comment]
I just added addins in the latest commits. I think they are neat.

Could I ask you to try and install from github again and let me know what you think? The behavior is described in the [README](https://github.com/lindeloev/job).

Launching the current script is just 
 1. Select everything 
 2. "Run selection as job" Addin

**Comment by wlandau** [comment]
Both addins work like a dream, thanks so much!
